/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/users/signup': {
    /** Signup */
    post: {
      requestBody: {
        content: {
          'application/json': {
            username: string;
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description User created */
        200: {
          content: {
            'application/json': {
              id?: number;
              username?: string;
              email?: string;
            };
          };
        };
        /** @description Conflict */
        409: {
          content: never;
        };
      };
    };
  };
  '/api/users/login': {
    /** Login */
    post: {
      requestBody: {
        content: {
          'application/json': {
            usernameOrEmail: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Tokens issued */
        200: {
          content: {
            'application/json': {
              token?: string;
              refreshToken?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
      };
    };
  };
  '/api/users/auth/send-code': {
    /** Send verification code */
    post: {
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
          };
        };
      };
      responses: {
        /** @description Code sent */
        200: {
          content: never;
        };
      };
    };
  };
  '/api/users/auth/verify-code': {
    /** Verify code */
    post: {
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            code: string;
          };
        };
      };
      responses: {
        /** @description Verified */
        200: {
          content: never;
        };
        /** @description Invalid */
        400: {
          content: never;
        };
      };
    };
  };
  '/api/users/auth/team/invite': {
    /** Invite user to team */
    post: {
      requestBody: {
        content: {
          'application/json': {
            /** @description Username or email */
            identifier: string;
          };
        };
      };
      responses: {
        /** @description Invite created */
        200: {
          content: never;
        };
      };
    };
  };
  '/api/users/auth/team/accept': {
    /** Accept team invite */
    post: {
      requestBody: {
        content: {
          'application/json': {
            /** @description Inviter user id */
            from?: number | null;
            /** @description Team id */
            teamId?: number | null;
          };
        };
      };
      responses: {
        /** @description Joined team */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
