name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Build backend
        run: npm run build:server

      - name: Run backend tests
        run: npm run test:run

      - name: Install UI dependencies
        run: npm --prefix ui ci --include=dev

      - name: Run UI tests
        run: npm --prefix ui run test:run

      - name: Build UI
        run: npm --prefix ui run build

      - name: Upload UI build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: ui/dist
          if-no-files-found: warn